spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: user
      password: password
      authentication-database: admin
      auto-index-creation: true